# Generated by Django 2.2 on 2019-05-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190512_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
