# Generated by Django 2.2 on 2019-05-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190512_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.BigIntegerField(),
        ),
    ]
