# Generated by Django 2.2 on 2019-05-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20190512_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.CharField(default='sushil', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.BigIntegerField(default='0'),
        ),
    ]
