# Generated by Django 2.2 on 2019-05-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20190512_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='character',
            field=models.CharField(default='arijit', max_length=255),
            preserve_default=False,
        ),
    ]
