# Generated by Django 2.2 on 2019-05-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20190526_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('decription', models.TextField(null=True)),
                ('images', models.CharField(max_length=255, null=True)),
                ('created_by', models.BigIntegerField(default=0)),
                ('updated_by', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('location', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
