# Generated by Django 2.2 on 2019-06-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('code', models.BigIntegerField(default='0')),
                ('user_id', models.BigIntegerField(default=0)),
                ('text', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
